path.data: data
path.logs: log
#log.level: trace
#log.debug: true

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    max_concurrency: 200000
    network:
      binding: 0.0.0.0:8000
#    tls:
#      enabled: true

flow:
  - name: async_bulk
    filter:
      - name: bulk_reshuffle
        when:
          contains:
            _ctx.request.path: /_bulk
        parameters:
          elasticsearch: dev
          level: node
          mode: async
          fix_null_id: true
          index_stats_analysis: true
          action_stats_analysis: true
          safety_parse: true
      - name: elasticsearch
        parameters:
          elasticsearch: dev  #elasticsearch configure reference name
          max_connection_per_host: 1000 #max tcp connection to upstream, default for all nodes
          max_response_size: -1 #default for all nodes
          balancer: weight
          refresh: # refresh upstream nodes list, need to enable this feature to use elasticsearch nodes auto discovery
            enabled: true
            interval: 60s
          filter:
            roles:
              exclude:
                - master
  - name: request_logging # this flow is used for request logging, refer to `router`'s `tracing_flow`
    filter:
      - name: request_logging
        parameters:
          queue_name: request_logging
          max_request_body_size: 1024
          max_response_body_size: 1024
          bulk_stats_details: true
router:
  - name: my_router
    default_flow: async_bulk
#    tracing_flow: request_logging


elasticsearch:
  - name: dev
    enabled: true
    endpoint: http://localhost:9200 # if your elasticsearch is using https, your gateway should be listen on as https as well
    traffic_control: #global traffic control
      max_bps_per_node: 20971520 #max total bytes send to es per node, 20MB/s
      max_qps_per_node: 50000 #max total requests send to es per node, 20k/s
    basic_auth: #used to discovery full cluster nodes, or check elasticsearch's health and versions
      username: test
      password: testtest
    discovery: # auto discovery elasticsearch cluster nodes
      enabled: true
      refresh:
        enabled: true
        interval: 60s

pipelines:
  - name: request_logging_index
    enabled: true
    start:
      joint: json_indexing
      enabled: true
      parameters:
        index_name: "gateway_requests"
        elasticsearch: "dev"
        input_queue: "request_logging"
        timeout: "1s"
        worker_size: 1
        bulk_size_in_mb: 10 #in MB
  - name: bulk_request_ingest
    enabled: true
    start:
      joint: bulk_indexing
      enabled: true
      parameters:
        elasticsearch: "dev"
        compress: true
        worker_size: 1
        bulk_size_in_mb: 5  #in MB
        idle_timeout_in_second: 5
        retry_delay_in_second: 1
        reject_retry_delay_in_second: 1
        max_retry_times: 3
        max_reject_retry_times: 3
        max_logged_request_body_size: 1024
        max_logged_response_body_size: 1024
        process_dead_letter_queue: true
