path.data: data
path.logs: log

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    max_concurrency: 200000
    network:
      binding: 0.0.0.0:8000
#    tls:
#      enabled: true

flow:
  - name: async_bulk
    filter:
      - bulk_reshuffle:
          when:
            contains:
              _ctx.request.path: /_bulk
          elasticsearch: dev
          level: node #cluster,node,shard,partition
          fix_null_id: true
      - elasticsearch:
          elasticsearch: dev  #elasticsearch configure reference name
          max_connection_per_node: 1000 #max tcp connection to upstream, default for all nodes
          max_response_size: -1 #default for all nodes
          balancer: weight
          refresh: # refresh upstream nodes list, need to enable this feature to use elasticsearch nodes auto discovery
            enabled: true
            interval: 60s
          filter:
            roles:
              exclude:
                - master

router:
  - name: my_router
    default_flow: async_bulk


elasticsearch:
  - name: dev
    enabled: true
    endpoint: http://192.168.3.188:9206 # if your elasticsearch is using https, your gateway should be listen on as https as well
#    endpoint: http://localhost:9200 # if your elasticsearch is using https, your gateway should be listen on as https as well
#    traffic_control: #global traffic control
#      max_bps_per_node: 20971520 #max total bytes send to es per node, 20MB/s
#      max_qps_per_node: 50000 #max total requests send to es per node, 20k/s
#    basic_auth: #used to discovery full cluster nodes, or check elasticsearch's health and versions
#      username: test
#      password: testtest
#    discovery: # auto discovery elasticsearch cluster nodes
#      enabled: true
#      refresh:
#        enabled: true
#        interval: 60s

pipeline:
  - name: bulk_request_ingest
    auto_start: true
    keep_running: true
    retry_delay_in_ms: 1000
    processor:
      - bulk_indexing:
          when:
            cluster_available: [ "dev" ]
          bulk_size_in_mb: 10
          bulk.compress: true
#          skip_info_missing: true
          fetch_max_messages: 1000
          queues:
            type: bulk_reshuffle

#disk_queue:
#  upload_to_s3: true
#  s3:
#    server: my_blob_store
#    location: cn-beijing-001
#    bucket: infini-store
#  max_msg_size: 209715200 #200MB
#  max_used_bytes: 102400
#  warning_free_bytes: 322122547200
#  reserved_free_bytes: 322122547200
#  max_bytes_per_file: 10576


#s3:
#  my_blob_store:
#    endpoint: "192.168.3.63:9000"
#    access_key: "minio"
#    access_secret: "gogoaminio"
    #  token:
#    ssl: false
