path.data: data
path.logs: log

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    max_concurrency: 1000
    network:
      binding: 0.0.0.0:8000

flow:
  - name: async_bulk
    filter:
      - bulk_reshuffle:
          when:
            contains:
              _ctx.request.path: /_bulk
          elasticsearch: prod
          level: cluster
          partition_size: 1
          fix_null_id: true
      - elasticsearch:
          elasticsearch: prod  #elasticsearch configure reference name
          max_connection_per_node: 1000 #max tcp connection to upstream, default for all nodes
          max_response_size: -1 #default for all nodes
          balancer: weight
          refresh: # refresh upstream nodes list, need to enable this feature to use elasticsearch nodes auto discovery
            enabled: true
            interval: 60s
          filter:
            roles:
              exclude:
                - master
router:
  - name: my_router
    default_flow: async_bulk
#    denied_client_ip_list:
#      - 133.37.54.23

elasticsearch:
  - name: prod
    enabled: true
    schema: http
    hosts:
      - 192.168.3.188:9206
    basic_auth:
      username: elastic
      password: password
    discovery:
      enabled: true
      refresh:
        enabled: true
        interval: 60s

pipeline:
  - name: bulk_request_ingest
    auto_start: true
    keep_running: true
    retry_delay_in_ms: 1000
    processor:
      - disorder_bulk_indexing:
          idle_timeout_in_seconds: 10
          max_connection_per_node: 1000
          worker_size: 3
          bulk:
            compress: false
            batch_size_in_mb: 10
            batch_size_in_docs: 50000
          queues:
            type: bulk_reshuffle
          when:
            cluster_available: [ "prod" ]

stats:
  enabled: false

disk_queue:
  sync_every_records: 10000
  sync_timeout_in_ms: 10000
memory_queue:
  capacity: 100000

queue:
  - name: async_bulk##cluster##prod
    type: memory
    label:
      type: bulk_reshuffle
      elasticsearch: prod

#floating_ip:
#  enabled: true
#  ip: 10.xxx.xxx.xxx
#  netmask: 255.255.255.0
#  interface: bond0
