path.data: data
path.logs: log

#show progress bar
progress_bar.enabled: true

elasticsearch:
  - name: source
    enabled: true
    endpoints:
      - http://10.0.1.15:9200
    basic_auth:
      username: elastic
      password: xxx
    #    traffic_control:
    #      max_qps_per_node: 1000
    discovery:
      enabled: true
      refresh:
        enabled: true
        interval: 60s
  - name: target
    enabled: true
    endpoints:
      - http://10.0.1.2:9200
    basic_auth:
      username: elastic
      password: xxx
    discovery:
      enabled: true
      refresh:
        enabled: true
        interval: 60s



pipeline:
  - name: index_diff_service
    auto_start: true
    processor:
    - dag:
        mode: wait_all
        parallel:
          - dump_hash: #dump es1's doc
              sort_document_fields: true
              indices: "test*"
              scroll_time: "10m"
              elasticsearch: "source"
#              query_string: "_id:c8es70pu46lgfdgmja9g-1646117763293610802-2"
#              fields: "doc_hash"
              output_queue: "source_docs"
              batch_size: 5000
              slice_size: 1
#              hash_func: "xxhash64"
          - dump_hash: #dump es2's doc
              indices: "test*"
              scroll_time: "10m"
#              fields: "doc_hash"
#              query_string: "_id:c8es70pu46lgfdgmja9g-1646117763293610802-2"
              batch_size: 5000
              slice_size: 1
#              hash_func: "xxhash64"
              elasticsearch: "target"
              output_queue: "target_docs"
        end:
          - index_diff:
              diff_queue: "diff_result"
              buffer_size: 10
              text_report: true #如果要存 es，这个开关关闭，开启 pipeline 的 diff_result_ingest 任务
              source_queue: 'source_docs'
              target_queue: 'target_docs'

#pipeline:
#  - name: diff_result_ingest
#    processor:
#      - json_indexing:
#          index_name: "diff_result"
#          elasticsearch: "source"
#          input_queue: "diff_result"
