path.data: data
path.logs: log
#progress_bar.enabled: true

elasticsearch:
  - name: source
    enabled: true
    endpoint: http://192.168.3.188:9204
    request_compress: true
    request_timeout: 30
#    max_bps_per_node: 52428800 #max total bytes send to es per node, 50MB/s
    basic_auth:
      username: test
      password: testtest
  - name: target
    enabled: true
    endpoint: http://192.168.3.188:9206
    request_compress: true
    request_timeout: 30
#    max_bps_per_node: 52428800 #max total bytes send to es per node, 50MB/s
    basic_auth: #used to discovery full cluster nodes, or check elasticsearch's health and versions
      username: test
      password: testtest

pipeline:
  - name: index_diff_service
    auto_start: true
    processor:
    - dag:
        parallel:
          - dump_hash: #dump es1's doc
              indices: "logstash-test7"
              scroll_time: "10m"
              elasticsearch: "source"
#              query: "field1:elastic"
#              fields: "doc_hash"
              output_queue: "source_docs"
              batch_size: 500
              slice_size: 3
#              hash_func: "xxhash64"
          - dump_hash: #dump es2's doc
              indices: "logstash-test7"
              scroll_time: "10m"
#              fields: "doc_hash"
#              query: "field1:elastic"
              batch_size: 500
              slice_size: 3
#              hash_func: "xxhash64"
              elasticsearch: "target"
              output_queue: "target_docs"
        end:
          - index_diff:
              diff_queue: "diff_result"
              buffer_size: 1
              text_report: true #如果要存 es，这个开关关闭，开启 pipeline 的 diff_result_ingest 任务
              source_queue: 'source_docs'
              target_queue: 'target_docs'

#pipeline:
#  - name: diff_result_ingest
#    processor:
#      - json_indexing:
#          index_name: "diff_result"
#          elasticsearch: "source"
#          input_queue: "diff_result"
