path.data: data
path.logs: log

elasticsearch:
  - name: prod
    enabled: true
    endpoint: https://192.168.3.98:9200
    basic_auth:
      username: test
      password: testtest
  - name: dev
    enabled: true
    endpoint: http://localhost:9200 # if your elasticsearch is using https, your gateway should be listen on as https as well
    basic_auth: #used to discovery full cluster nodes, or check elasticsearch's health and versions
      username: test
      password: testtest

modules:
  - name: elastic
    enabled: true
    elasticsearch: dev
    store:
      enabled: true
    monitoring:
      enabled: false
    orm:
      enabled: true
      init_template: true
      template_name: ".gateway-default"
      index_prefix: "gateway_"

  - name: pipeline
    enabled: true
    runners:
      - name: my_scroll1
        enabled: false
        pipeline_id: es_scroll_a
        schedule: "once"
        max_go_routine: 1
        threshold_in_ms: 0
        timeout_in_ms: 5000
      - name: my_scroll2
        enabled: false
        pipeline_id: es_scroll_b
        schedule: "once"
        max_go_routine: 1
        threshold_in_ms: 0
        timeout_in_ms: 5000
      - name: diff_result_ingest
        enabled: false
        pipeline_id: diff_result_ingest
        schedule: "once"
        max_go_routine: 1
        threshold_in_ms: 0
        timeout_in_ms: 5000


pipelines:
  #使用两个 scroll 任务并行读取两个索引的文档
  - name: es_scroll_a
    input:
      joint: es_scroll
      enabled: false
      parameters:
        indices: "medcl-a"
        scroll_time: "10m"
        batch_size: 10000
        slice_size: 1
        elasticsearch: "dev"
        output_queue: "source_docs"
  - name: es_scroll_b
    input:
      joint: es_scroll
      enabled: false
      parameters:
        indices: "medcl-b"
        scroll_time: "10m"
        batch_size: 10000
        slice_size: 1
        elasticsearch: "dev"
        output_queue: "target_docs"
  # 消费 diff 结果并保存到 Elasticsearch 用于查看两个索引的 diff 结果
  - name: diff_result_ingest
    start:
      joint: json_indexing
      enabled: false
      parameters:
        index_name: "diff_result"
        index_type: "doc"
        elasticsearch: "prod"
        input_queue: "diff_result"
        timeout: "1s"
        worker_size: 1
        bulk_size_in_mb: 1 #in MB

# 进行 diff 的服务
index_diff:
  enabled: false
  diff_queue: "diff_result"
  buffer_size: 10
  source:
    input_queue: 'source_docs'
  target:
    input_queue: 'target_docs'

