path.data: data
path.logs: log

elasticsearch:
  - name: source
    enabled: true
    endpoint: http://192.168.3.188:9204
    basic_auth:
      username: test
      password: testtest
  - name: target
    enabled: true
    endpoint: http://192.168.3.188:9206
    basic_auth: #used to discovery full cluster nodes, or check elasticsearch's health and versions
      username: test
      password: testtest

pipelines_v2:
  - name: index_diff_service
    processors:
    - dag:
        parallel:
          - dump_hash: #dump es1's doc
              indices: "medcl-a"
              scroll_time: "10m"
              elasticsearch: "source"
#              query: "field1:elastic"
#              fields: "name,age"
              output_queue: "source_docs"
              batch_size: 10000
              slice_size: 5
          - dump_hash: #dump es2's doc
              indices: "medcl-a"
              scroll_time: "10m"
#              query: "field1:elastic"
              batch_size: 10000
              slice_size: 5
              elasticsearch: "target"
              output_queue: "target_docs"
        end:
          - index_diff:
              diff_queue: "diff_result"
              buffer_size: 1
              text_report: true #如果要存 es，这个开关关闭，开启 pipeline 的 diff_result_ingest 任务
              source_queue: 'source_docs'
              target_queue: 'target_docs'

#pipelines_v2:
#  - name: diff_result_ingest
#    processors:
#      - json_indexing:
#          index_name: "diff_result"
#          elasticsearch: "source"
#          input_queue: "diff_result"