path.data: data
path.logs: log
#path.plugins: /Users/medcl/go/src/infini.sh/gateway/proxy/plugin

api:
  enabled: true
  network:
    binding: 0.0.0.0:2900
    skip_occupied_port: true
  tls:
    enabled: false

elasticsearch:
- name: default
  enabled: true
  endpoint: https://127.0.0.1:9200
  version: 7.6.0
  index_prefix: proxy-
  basic_auth:
    username: elastic
    password: changeme
- name: backup
  enabled: true
  endpoint: http://localhost:9200
#  endpoint: https://192.168.3.98:9200
  version: auto
  index_prefix: proxy-
  basic_auth:
    username: elastic
    password: 13A1EcwWs1He6w3BXHuJ


cache:
  enabled: false
  redis:
    host: localhost
    port: 6379
    password: ""
    db: 0
  #Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
  ttl: 60s

proxy:
  enabled: true
  network:
    binding: 0.0.0.0:8000
    skip_occupied_port: true
    reuse_port: true
  tls:
    enabled: false

  cache:
    enabled: true
    ttl: 10s
    max_cached_item: 1000
  balancer: weight
  pass_through: ["_update","_search", "_count", "_analyze", "_mget", "_doc", "_mtermvectors", "_msearch", "_search_shards", "_suggest", "_validate", "_explain", "_field_caps", "_rank_eval", "_aliases"]
  upstream:
    - name: primary
      enabled: false
      weight: 10
      max_connection: 1000
      mode: pass_through
      #    cache:
      #      enabled: false
      rate_limit:
        max_qps: 20000
      queue_name: primary
      max_queue_depth: -1
      timeout: 60s
      elasticsearch: default
    - name: backup
      enabled: true
      max_connection: 1000
      weight: 10
      mode: proxy
      #    cache_enabled: false
      queue_name: backup
      max_queue_depth: -1
      timeout: 60s
      elasticsearch: backup

statsd:
  enabled: true
  host: 192.168.3.98
  port: 8125
  namespace: gateway.

plugins:
- name: floating_ip
  enabled: false
  ip: 192.168.3.221
  netmask: 255.255.255.0
  interface: en0
  priority: 100

pipelines:
- name: primary
  start:
    joint: index
    enabled: true
  process: []
  error:
    joint: logging
    enabled: true
- name: backup
  start:
    joint: index
    enabled: true
  process: []
  error:
    joint: logging
    enabled: true


modules:
- name: elastic
  elasticsearch: default
  enabled: true
  indexer_enabled: false
  store_enabled: false
  orm_enabled: false

- name: web
  enabled: false
  tls:
     enabled: true
  network:
     binding: 127.0.0.1:9000

- name: pipeline
  enabled: true
  runners:
    - name: primary
      enabled: true
      input_queue: primary
      max_go_routine: 3
      threshold_in_ms: 0
      timeout_in_ms: 5000
      pipeline_id: primary

    - name: backup
      enabled: true
      input_queue: backup
      max_go_routine: 1
      threshold_in_ms: 0
      timeout_in_ms: 5000
      pipeline_id: backup
