path.data: data
path.logs: log

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    max_concurrency: 10000
    network:
      binding: 0.0.0.0:8000
#    tls:
#      enabled: true

flow:
  - name: default_flow
    filter:
      - get_cache:
      - bulk_reshuffle:
          when:
            contains:
              _ctx.request.path: /_bulk
          elasticsearch: dev
          level: node
          fix_null_id: true
      - elasticsearch:
          elasticsearch: dev  #elasticsearch configure reference name
          max_connection_per_node: 1000 #max tcp connection to upstream, default for all nodes
          max_response_size: -1 #default for all nodes
          balancer: weight
          refresh: # refresh upstream nodes list, need to enable this feature to use elasticsearch nodes auto discovery
            enabled: true
            interval: 60s
      - set_cache:
  - name: logging # this flow is used for request logging, refer to `router`'s `tracing_flow`
    filter:
      - stats:
      - logging:
          queue_name: request_logging
          max_request_body_size: 10240
          max_response_body_size: 10240
          when: #>1s or none-200 requests will be logged
            or:
              - not:
                  or:
                    - equals:
                        _ctx.request.path: "/favicon.ico"
                    - in:
                        _ctx.response.status: [200,201]
                    - in:
                        _ctx.request.path: ["/sw.js"]
              - range:
                  _ctx.elapsed.gte: 1000
router:
  - name: my_router
    default_flow: default_flow
    tracing_flow: logging

elasticsearch:
- name: dev
  enabled: true
  schema: http
  hosts:
    - 192.168.3.188:9206
    - 127.0.0.1:9200
  traffic_control: #global traffic control
    max_bps_per_node: 209715200 #max total bytes send to es per node, 200MB/s
    max_qps_per_node: 20000 #max total requests send to es per node, 20k/s
  basic_auth: #used to discovery full cluster nodes, or check elasticsearch's health and versions
    username: test
    password: testtest
  discovery: # auto discovery elasticsearch cluster nodes
    enabled: true
    refresh:
      enabled: true
      interval: 60s

pipeline:
- name: request_logging_index
  auto_start: true
  keep_running: true
  processor:
    - json_indexing:
        index_name: "gateway_requests"
        elasticsearch: "dev"
        input_queue: "request_logging"
        idle_timeout_in_seconds: 1
        worker_size: 1
        bulk_size_in_mb: 10 #in MB
        when:
          cluster_available: [ "dev" ]
- name: bulk_request_ingest
  auto_start: true
  keep_running: true
  processor:
    - bulk_indexing:
        elasticsearch: "dev"
        max_worker_size: 10
        bulk.compress: true
        bulk_size_in_mb: 50  #in MB
        retry_delay_in_seconds: 5
        queues: #filter by labels
          type: bulk_reshuffle
        when:
          cluster_available: [ "dev" ]