path.data: data
path.logs: log
#log.level: trace
#log.debug: true

#api:
#  enabled: true
#  network:
#    binding: 127.0.0.1:2900

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    max_concurrency: 1000
#    reduce_memory_usage: true
    network:
      binding: 0.0.0.0:8000
#    tls:
#      enabled: true

flow:
  - name: echo
    filter_v2:
      - set_response:
          when:
            equals:
              _ctx.request.path: /favicon.ico
          status: 404
          content_type: "text/plain; charset=utf-8"
          body: "oops, favicon.ico"
      - set_response:
          when:
            equals:
              _ctx.request.path: /
          status: 404
          content_type: "text/plain; charset=utf-8"
          body: "root path"
  - name: cache_first
    filter:
#      - name: translog
#        parameters:
#          category: dev
#          filename: translog.log
#          compress: true
#          max_file_age: 2
#          max_file_count: 50
#          max_file_size_in_mb: 1024
      - name: get_cache
        parameters:
          pass_patterns:
            - _cat
      - name: bulk_reshuffle
        when:
          contains:
            _ctx.request.path: /_bulk
        parameters:
          elasticsearch: dev
          level: node
          mode: async
          fix_null_id: true
          index_stats_analysis: true
          action_stats_analysis: true
          validate_each_line: false
          validate_metadata: false
          validate_request: false
          validate_payload: false
          max_logged_response_body_size: 4096
      - name: elasticsearch
        parameters:
          elasticsearch: dev  #elasticsearch configure reference name
          max_connection_per_host: 100 #max tcp connection to upstream, default for all nodes
          max_response_size: -1 #default for all nodes
          balancer: weight
          refresh: # refresh upstream nodes list, need to enable this feature to use elasticsearch nodes auto discovery
            enabled: true
            interval: 60s
          filter:
            tags:
                exclude:
                - temp: cold
            roles:
              exclude:
                - master
      - name: set_cache
        parameters:
          cache_ttl: 10s
  - name: request_logging # this flow is used for request logging, refer to `router`'s `tracing_flow`
    filter:
      - name: request_logging
        parameters:
          queue_name: request_logging
          max_request_body_size: 1024
          max_response_body_size: 1024
#          min_elapsed_time_in_ms: 500 # only record slow requests
          bulk_stats_details: true
router:
  - name: my_router
#    default_flow: echo
    default_flow: cache_first
#    tracing_flow: request_logging


elasticsearch:
- name: dev
  enabled: true
  endpoint: http://localhost:9200 # if your elasticsearch is using https, your gateway should be listen on as https as well
  traffic_control: #global traffic control
    max_bps_per_node: 209715200 #max total bytes send to es per node, 200MB/s
    max_qps_per_node: 20000 #max total requests send to es per node, 20k/s
  basic_auth: #used to discovery full cluster nodes, or check elasticsearch's health and versions
    username: test
    password: testtest
  discovery: # auto discovery elasticsearch cluster nodes
    enabled: true
    refresh:
      enabled: true
      interval: 60s

#elastic:
#  elasticsearch: dev
#  store:
#    enabled: true
#  monitoring:
#    enabled: false
#  orm:
#    enabled: true
#    init_template: true
#    template_name: ".gateway-default"
#    index_prefix: "gateway_"

#pipelines_v2:
#  - name: index_diff_service
#    processors:
#    - echo: #ready, set, go
#        message: read,set,go
#    - dag:
#        mode: first_win #first_win, wait_all
#        parallel:
#          - echo: #player1
#              message: player1
#          - echo: #player2
#              message: player2
#          - echo: #player3
#              message: player3
#        end:
#          - echo: #checking score
#              message: checking score
#          - echo: #announce champion
#              message: 'announce champion'
#    - echo: #done
#        message: racing finished

pipelines:
- name: request_logging_index
  enabled: true
  start:
    joint: json_indexing
    enabled: true
    parameters:
      index_name: "gateway_requests"
      elasticsearch: "dev"
      input_queue: "request_logging"
      timeout: "1s"
      worker_size: 1
      bulk_size_in_mb: 10 #in MB
- name: bulk_request_ingest
  enabled: true
  start:
    joint: bulk_indexing
    enabled: true
    parameters:
      elasticsearch: "dev"
      compress: false
      worker_size: 1
      bulk_size_in_mb: 10  #in MB
      retry_delay_in_second: 5
      process_failure_queue: true #process failed bulk messages
#      queues: #process other bulk queue
#        - dev-node-failure
#        - dev-invalid


floating_ip:
  enabled: false
#  ip: 192.168.3.234      #yep, it's optional, infini-gateway could detect one but maybe not the right one
##  netmask: 255.255.255.0 #optional
##  interface: en1         #optional

statsd:
  enabled: true
  host: 127.0.0.1
  port: 8125
  protocol: udp
  namespace: gateway.
  buffer_size: 102400

#redis:
#  enabled: true
#  host: localhost
#  port: 6379
#
#queue:
#  - name: dev-node-yNgVusnXSgqvP2fZeGFSLw
#    type: redis
