version: "3.5"

services:
  infini-gateway:
    image: infinilabs/gateway:latest
#    build:
#      context: .
#      dockerfile: ./Dockerfile

    ports:
      - 2900:2900
      - 8000:8000
      - 61111:61111
    container_name: "infini-gateway"
    volumes:
      - ../gateway.yml:/gateway.yml

volumes:
  dist:
